# Default values for odk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
odk:
  repository: "ehealthafrica/aether-odk"
name: odk
project: aether
release: 0.5.2
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
environment: "dev"
ums_url: ums-dev
kernel_url: http://kernel
# FIXME: configurable
domain: aether.local
trusted_origins: .ehealthafrica.org,.gather2.org
namespace:
  create: false
application:
  secret: secrets
  data_mount: /media
database:
  secret: database-credentials
provider:
  aws: false
ingress:
  enabled: true

  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:387526361725:certificate/dcd71c49-1b5b-4b19-bd2d-6de98a3f6477"
    alb.ingress.kubernetes.io/security-groups: "alb-ingress-controller.dev.k8s.eha.to"
