# Default values for odk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  tag: stable-alpine
  pullPolicy: IfNotPresent
odk:
  repository: "ehealthafrica/aether-odk"
name: odk
project: aether
release: 0.6.0
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
environment: "dev"
ums_url: ums-dev
kernel_url: http://kernel
kernel_url_test: http://kernel
domain: aether.local
trusted_origins: .aether.local
debug: false
testing: false
webserverPort: 8000
liveEdit:
  enabled: false
namespace:
  create: false
application:
  command: start
  secret: odk-secrets
  data_mount: /media
  admin_user: admin
database:
  secret: database-credentials
provider:
  aws: false
ingress:
  enabled: true
  hosts:
    - odk.aether.local
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
