apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  default.conf: |
    server {
      {{- if .Values.debug }}
      error_log /var/log/nginx/error.log info;
      {{- else }}
      access_log off;
      {{- end }}

      location /health {
        proxy_pass http://127.0.0.1:{{ .Values.app.port }};
      }
    }

    server {
      listen      80
      charset     utf-8;
      server_name {{ .Release.Name }}.{{ .Values.domain }}
                  {{ .Release.Name }};
      {{- if .Values.debug }}
      error_log   /var/log/nginx/error.log info;
      {{- else }}
      access_log  off;
      {{- end }}

      # Max upload size
      client_max_body_size 75M;   # adjust to taste

      if ($http_x_forwarded_proto != 'https') {
       return 301 https://$host$request_uri;
      }

      location /static/ {
        alias /var/www/static/;
      }

      # Finally, send all non-static requests to the Django server.
      location / {
        proxy_pass http://127.0.0.1:{{ .Values.app.port }};
        proxy_set_header        Host               $host;
        proxy_set_header        X-Real-IP          $remote_addr;
        proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Host   $host:443;
        proxy_set_header        X-Forwarded-Server $host;
        proxy_set_header        X-Forwarded-Port   443;
        proxy_set_header        X-Forwarded-Proto  https;
        include    /etc/nginx/uwsgi_params; # or the uwsgi_params you installed manually
      }
    }
