{{- if .Values.provider.aws -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This is not used by the provisioner, but is required by the PVC.
      storage: 1Mi
{{- else -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pv0001
  resources:
    requests:
      storage: 1Mi
{{- end -}}
