apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  host:
  password:
  user:
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  ui-django-admin-password:
  ui-django-secret-key:
  ui-database-password:
  ui-kernel-token:
